#!/bin/bash -e

domain=noyuno.space
child=(pi.noyuno.space v.noyuno.space)
user=noyuno
ledir=/etc/letsencrypt/live/$store
watchbase=$(cd $(dirname $0); pwd)
deploybase=$(cd $(dirname $0); pwd)
watchdir=$watchbase/recv

